### ISSUE TITLE
Breakout Room

### ISSUE THREAD

**Issue by Nishant-Kumar-2002** [rootCircle/Zoom-AutoRecorder#10]
Can we record breakout room using this and auto upload to cloud?

**Comment by rootCircle** [comment]
This app just records the current user view, I haven't tested them with breakout rooms, but I believe it surely should work! If it doesn't only minor changes might be needed (PRs are welcome!)

Uploading to cloud is still not supported, as this app still relies on OBS for recording and doesn't have much amount of freedom when it comes to recording screen! However, we can support that easily using any cloud provider supporting storage buckets easily, forcing output directory to a fixed temp location!
